<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ProductSale;
use AppBundle\Entity\ProductStock;

/**
 * ProductCrossoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCrossoutRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * searchBy
     *
     * @param array $terms
     * @param $paginator
     * @return mixed
     */
    public function searchBy(array $terms, $paginator)
    {
        $query = $this->getQueryByTerms($terms);
        $pagination = $paginator->paginate($query, $terms['page'], $terms['limit']);

        return $pagination;
    }

    /**
     * findAllBy
     *
     * @param array $terms
     * @return array
     */
    public function findAllBy(array $terms)
    {
        $query = $this->getQueryByTerms($terms);
        return $query->getQuery()->getResult();
    }


    /**
     * getQueryByTerms
     *
     * @param $terms
     * @param $page
     * @param int $limit
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryByTerms($terms)
    {
        /* @var $qb \Doctrine\ORM\QueryBuilder */
        $qb = $this->createQueryBuilder('pc');

        $qb->innerJoin(ProductSale::class, 'ps', 'WITH', 'pc.productSaleId=ps.id');

        // filters data
        if (isset($terms['documents']) && $terms['documents'] != "") {
            $defined = false;
            foreach($qb->getDQLPart('join')['pc'] as $item) {
                if ($item->getJoin() == ProductStock::class) $defined = true;
            }
            if ($defined === false) {
                $qb->innerJoin(ProductStock::class, 'p', 'WITH', 'ps.productId=p.id');
            }
            $qb->andWhere('p.documents = :documents');
            $qb->setParameter('documents', $terms['documents']);
        }
        if (isset($terms['priceFrom']) && !empty($terms['priceFrom'])) {
            $qb->andWhere('pc.price >= :price_from');
            $qb->setParameter('price_from', $terms['priceFrom']);
        }
        if (isset($terms['priceTo']) && !empty($terms['priceTo'])) {
            $qb->andWhere('pc.price <= :price_to');
            $qb->setParameter('price_to', $terms['priceTo']);
        }
        if (isset($terms['dateFrom']) && !empty($terms['dateFrom'])) {
            $dateFrom = \DateTime::createFromFormat('Y.m.d', $terms['dateFrom']);
            $qb->andWhere('pc.date >= :date_from');
            $qb->setParameter('date_from', $dateFrom->format('Y-m-d 00:00:00'));
        }
        else {
            // by default select date from beginning of the year
            $qb->andWhere('pc.date >= :price_from');
            $date = new \DateTime();
            $mounth = $date->format('m');
            if ($mounth >= 3) {
                $date->setDate($date->format('Y'), '01','01');
                $date->setTime('0','0','0');
            }
            else {
                $date->setDate($date->format('Y')-1, '01','01');
                $date->setTime('0','0','0');
            }
            $qb->setParameter('price_from', $date);
        }
        if (isset($terms['dateTo']) && !empty($terms['dateTo'])) {
            $dateTo = \DateTime::createFromFormat('Y.m.d', $terms['dateTo']);
            $qb->andWhere('pc.date <= :date_to');
            $qb->setParameter('date_to', $dateTo->format('Y-m-d 23:59:59'));
        }
        if (isset($terms['providerId']) && !empty($terms['providerId'])) {
            $defined = false;
            foreach($qb->getDQLPart('join')['pc'] as $item) {
                if ($item->getJoin() == ProductStock::class) $defined = true;
            }
            if ($defined === false) {
                $qb->innerJoin(ProductStock::class, 'p', 'WITH', 'ps.productId=p.id');
            }
            $qb->andWhere('p.providerId = :provider_id')
                ->setParameter('provider_id', $terms['providerId']);
        }
        if (isset($terms['title']) && !empty($terms['title'])) {
            $defined = false;
            foreach($qb->getDQLPart('join')['pc'] as $item) {
                if ($item->getJoin() == ProductStock::class) $defined = true;
            }
            if ($defined === false) {
                $qb->innerJoin(ProductStock::class, 'p', 'WITH', 'ps.productId=p.id');
            }
            $qb->andWhere('p.title LIKE :title')
                ->setParameter('title', '%'.$terms['title'].'%');
        }

        // sort by data
        if (isset($terms['sortCol']) && !empty($terms['sortCol'])) {
            $order = $terms['sortOrder'] ? $terms['sortOrder'] : 'ASC';
            if ($terms['sortCol'] == 'total') {
                $qb->orderBy('ps.qty', $order);
            }
            if ($terms['sortCol'] == 'price-purchase-byn') {
                $defined = false;
                foreach($qb->getDQLPart('join')['pc'] as $item) {
                    if ($item->getJoin() == ProductStock::class) $defined = true;
                }
                if ($defined === false) {
                    $qb->innerJoin(ProductStock::class, 'p', 'WITH', 'ps.productId=p.id');
                }
                $qb->orderBy('p.priceByn', $order);
            }
            if ($terms['sortCol'] == 'price-purchase') {
                $defined = false;
                foreach($qb->getDQLPart('join')['pc'] as $item) {
                    if ($item->getJoin() == ProductStock::class) $defined = true;
                }
                if ($defined === false) {
                    $qb->innerJoin(ProductStock::class, 'p', 'WITH', 'ps.productId=p.id');
                }
                $qb->orderBy('p.price', $order);
            }
            if ($terms['sortCol'] == 'price-sale') {
                $qb->orderBy('ps.price', $order);
            }
            if ($terms['sortCol'] == 'price-crossout') {
                $qb->orderBy('pc.price', $order);
            }
            if ($terms['sortCol'] == 'date-crossout') {
                $qb->orderBy('pc.date', $order);
            }
        }
        else {
            // default sort
            $qb->orderBy('pc.date', 'DESC');
        }

        return $qb;
    }

    /**
     * getStats
     *
     * @return array
     */
    public function getStats()
    {
        $stats = [];
        // current mounth
        $qb = $this->createQueryBuilder('pc')
            ->select('SUM(pc.price*ps.qty) AS sum_price, SUM(ps.qty) AS sum_qty')
            ->innerJoin(ProductSale::class,'ps', 'WITH', 'pc.productSaleId=ps.id')
            //->groupBy('ps.productId')
            ->where('pc.date > :current_mounth_start AND pc.date < :current_mounth_end')
            ->setParameter('current_mounth_start', date('Y-m-01 00:00:00') )
            ->setParameter('current_mounth_end', date('Y-m-31 23:59:59') );
        $result = $qb->getQuery()->getResult();
        if (isset($result[0]['sum_price']) && !empty($result[0]['sum_price'])) {
            $stats['cur_mounth_price'] = $result[0]['sum_price'];
            $stats['cur_mounth_qty'] = $result[0]['sum_qty'];
        }
        else {
            $stats['cur_mounth_price'] = 0;
            $stats['cur_mounth_qty'] = 0;
        }

        // prev mounth
        $qb = $this->createQueryBuilder('pc')
            ->select('SUM(pc.price*ps.qty) AS sum_price, SUM(ps.qty) AS sum_qty')
            ->innerJoin(ProductSale::class,'ps', 'WITH', 'pc.productSaleId=ps.id')
            //->groupBy('ps.productId')
            ->where('pc.date > :prev_mounth_start AND pc.date < :prev_mounth_end')
            ->setParameter('prev_mounth_start', date('Y-m-01 00:00:00', strtotime('last month')) )
            ->setParameter('prev_mounth_end', date('Y-m-31 23:59:59', strtotime('last month')) );
        $result = $qb->getQuery()->getResult();
        if (isset($result[0]['sum_price']) && !empty($result[0]['sum_price'])) {
            $stats['prev_mounth_price'] = $result[0]['sum_price'];
            $stats['prev_mounth_qty'] = $result[0]['sum_qty'];
        }
        else {
            $stats['prev_mounth_price'] = 0;
            $stats['prev_mounth_qty'] = 0;
        }

        // current quarter
        $quarter = ceil(date('n', time()) / 3);
        $quarter_mounth_end = $quarter*3;
        $quarter_mounth_start = $quarter*3 - 3;

        $quarter_date_start = new \DateTime();
        $quarter_date_start->setDate(date('Y'), $quarter_mounth_start , 1);
        $quarter_date_start->setTime(0,0,0);

        $quarter_date_end = new \DateTime();
        $quarter_date_end->setDate(date('Y'), $quarter_mounth_end+1 , 0);
        $quarter_date_end->setTime(23,59,59);

        $qb = $this->createQueryBuilder('pc')
            ->select('SUM(ps.price*ps.qty) AS sum_price, SUM(ps.qty) AS sum_qty')
            ->innerJoin(ProductSale::class,'ps', 'WITH', 'pc.productSaleId=ps.id')
            //->groupBy('ps.productId')
            ->where('pc.date > :quarter_date_start AND pc.date < :quarter_date_end')
            ->setParameter('quarter_date_start', $quarter_date_start->format('Y-m-d H:i:s') )
            ->setParameter('quarter_date_end', $quarter_date_end->format('Y-m-d H:i:s') );
        $result = $qb->getQuery()->getResult();
        if (isset($result[0]['sum_price']) && !empty($result[0]['sum_price'])) {
            $stats['cur_quarter_price'] = $result[0]['sum_price'];
            $stats['cur_quarter_qty'] = $result[0]['sum_qty'];
        }
        else {
            $stats['cur_quarter_price'] = 0;
            $stats['cur_quarter_qty'] = 0;
        }

        // prev quarter
        $quarter = ceil(date('n', time()) / 3)-1;
        $quarter_mounth_end = $quarter*3;
        $quarter_mounth_start = $quarter*3 - 3;

        $quarter_date_start = new \DateTime();
        $quarter_date_start->setDate(date('Y'), $quarter_mounth_start , 1);
        $quarter_date_start->setTime(0,0,0);

        $quarter_date_end = new \DateTime();
        $quarter_date_end->setDate(date('Y'), $quarter_mounth_end+1 , 0);
        $quarter_date_end->setTime(23,59,59);

        $qb = $this->createQueryBuilder('pc')
            ->select('SUM(pc.price*ps.qty) AS sum_price, SUM(ps.qty) AS sum_qty')
            ->innerJoin(ProductSale::class,'ps', 'WITH', 'pc.productSaleId=ps.id')
            //->groupBy('ps.productId')
            ->where('pc.date > :quarter_date_start AND pc.date < :quarter_date_end')
            ->setParameter('quarter_date_start', $quarter_date_start->format('Y-m-d H:i:s') )
            ->setParameter('quarter_date_end', $quarter_date_end->format('Y-m-d H:i:s') );
        $result = $qb->getQuery()->getResult();
        if (isset($result[0]['sum_price']) && !empty($result[0]['sum_price'])) {
            $stats['prev_quarter_price'] = $result[0]['sum_price'];
            $stats['prev_quarter_qty'] = $result[0]['sum_qty'];
        }
        else {
            $stats['prev_quarter_price'] = 0;
            $stats['prev_quarter_qty'] = 0;
        }

        // current year
        $qb = $this->createQueryBuilder('pc')
            ->select('SUM(pc.price*ps.qty) AS sum_price, SUM(ps.qty) AS sum_qty')
            ->innerJoin(ProductSale::class,'ps', 'WITH', 'pc.productSaleId=ps.id')
            //->groupBy('ps.productId')
            ->where('pc.date > :current_year_start AND pc.date < :current_year_end')
            ->setParameter('current_year_start', date('Y-01-01 00:00:00') )
            ->setParameter('current_year_end', date('Y-12-31 23:59:59') );
        $result = $qb->getQuery()->getResult();
        if (isset($result[0]['sum_price']) && !empty($result[0]['sum_price'])) {
            $stats['cur_year_price_byn'] = $result[0]['sum_price'];
            $stats['cur_year_qty'] = $result[0]['sum_qty'];
        }
        else {
            $stats['cur_year_price_byn'] = 0;
            $stats['cur_year_qty'] = 0;
        }

        return $stats;
    }

    /**
     * Get Total
     *
     * @return array
     */
    public function getTotal()
    {
        $total = [];

        $qb = $this->createQueryBuilder('pc')
            ->select('SUM(pc.price*ps.qty) AS total_crossout_price,
                            SUM(ps.qty) AS total_qty,
                            SUM(ps.price*ps.qty) AS total_sale_price,
                            SUM(p.price*ps.qty) AS total_purchase_price,
                            SUM(p.priceByn*ps.qty) AS total_purchase_price_byn')
            ->leftJoin(ProductSale::class, 'ps','WITH', 'pc.productSaleId=ps.id')
            ->leftJoin(ProductStock::class, 'p','WITH', 'ps.productId=p.id');

        $result = $qb->getQuery()->getResult();
        if (isset($result[0])) {
            $total['qty'] = ($result[0]['total_qty']) ? $result[0]['total_qty'] : 0;
            $total['sale_price'] = ($result[0]['total_sale_price']) ? $result[0]['total_sale_price'] : 0;
            $total['crossout_price'] = ($result[0]['total_crossout_price']) ? $result[0]['total_crossout_price'] : 0;
            $total['purchase_price'] = ($result[0]['total_purchase_price']) ? $result[0]['total_purchase_price'] : 0;
            $total['purchase_price_byn'] = ($result[0]['total_purchase_price_byn']) ? $result[0]['total_purchase_price_byn'] : 0;
        }

        return $total;
    }

    /**
     * getTotalBy
     *
     * @param $terms
     */
    public function getTotalBy($terms)
    {
        unset($terms['sortCol']);
        $total = [];
        $qb = $this->getQueryByTerms($terms);
        $qb->select('SUM(pc.price*ps.qty) AS total_crossout_price,
                           SUM(ps.qty) AS total_qty,
                           SUM(ps.price*ps.qty) AS total_sale_price,
                           SUM(p.price*ps.qty) AS total_purchase_price,
                           SUM(p.priceByn*ps.qty) AS total_purchase_price_byn');

        $defined = false;
        foreach($qb->getDQLPart('join')['pc'] as $item) {
            if ($item->getJoin() == ProductStock::class) $defined = true;
        }
        if ($defined === false) {
            $qb->innerJoin(ProductStock::class, 'p', 'WITH', 'ps.productId=p.id');
        }

        $result = $qb->getQuery()->getResult();
        if (isset($result[0]['total_qty']) && !empty($result[0]['total_qty'])) {
            $total['qty'] = $result[0]['total_qty'];
            $total['sale_price'] = $result[0]['total_sale_price'];
            $total['crossout_price'] = $result[0]['total_crossout_price'];
            $total['purchase_price'] = $result[0]['total_purchase_price'];
            $total['purchase_price_byn'] = $result[0]['total_purchase_price_byn'];
        }

        return $total;
    }

    /**
     * findStatsByMounth
     *
     * @return array
     */
    public function findStatsByMonth()
    {
        $date = new \DateTime();
        $qb = $this->createQueryBuilder('pc')
            ->select('SUM(pc.price*pc.qty) AS total_price,
                            SUM(pc.qty) AS total_qty,
                            SUM(pc.priceByn*pc.qty) AS total_price_byn,
                            YEAR(pc.created) AS year,
                            MONTH(pc.created) AS month')
            ->where('YEAR(pc.created) = :cur_year')
            ->setParameter('cur_year', $date->format('Y'))
            ->groupBy('year, month');

        $tmp = $qb->getQuery()->getResult();
        $result = [];
        foreach ($tmp as $item) {
            $result[$item['month']] = $item;
        }

        return $result;
    }
}
