<?php

namespace AppBundle\Repository;

/**
 * ProfitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfitRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * findByMonth
     *
     * @param null $month
     */
    public function findByMonth($month = null, $terms = [])
    {
        $date = new \DateTime();
        if (is_null($month)) {
            $month = $date->format('m')*1;
        }
        else {
            $date->setDate($date->format('Y'), $month, 1);
        }

        $qb = $this->createQueryBuilder('p')
                    ->select('DAY(p.date) AS day,
                                    p.income AS income,
                                    p.outcome AS outcome')
                    ->where('MONTH(p.date) = :month')
                    ->setParameter('month', $month);
        $profitTmpResult = $qb->getQuery()->getResult();
        $profitResult = [];
        foreach ($profitTmpResult as $item) {
            $profitResult[$item['day']] = $item;
        }

        $repoSale = $this->getEntityManager()->getRepository('AppBundle:ProductSale');
        $daysSaleProfit = $repoSale->findDaysProfitByMonth($month, $terms);

        $result = [];
        $countDays = $date->format('t')*1;
        for($i=1;$i<=$countDays;$i++) {
            if (isset($daysSaleProfit[$i])) {
                $result[$i]['profit'] = $daysSaleProfit[$i]['total_price'];
            } else {
                $result[$i]['profit'] = 0;
            }

            if (isset($profitResult[$i])) {
                $result[$i]['income'] = $profitResult[$i]['income'];
            } else {
                $result[$i]['income'] = 0;
            }

            if (isset($profitResult[$i])) {
                $result[$i]['outcome'] = $profitResult[$i]['outcome'];
            } else {
                $result[$i]['outcome'] = 0;
            }

            $result[$i]['total'] = $result[$i]['profit'] + $result[$i]['income'] - $result[$i]['outcome'];
        }

        return $result;
    }
}
