<?php

namespace AppBundle\Repository;

/**
 * CurrencyLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateHistoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCurrentDate()
    {
        $date = new \DateTime();

        $result = $this->createQueryBuilder('r')
            ->where('r.date > :start_date AND r.date < :end_date')
            ->setParameter('start_date', $date->format('Y-m-d 00:00:00') )
            ->setParameter('end_date', $date->format('Y-m-d 99:99:99') )
            ->getQuery()
            ->getResult();

        return $result;
    }
}
